#!/bin/bash/env bash
# Find the PID of the 4-to_infinity_and_beyond script

PID=$(pgrep 4-to_infinity_and_beyond)

# Check if the process was found
if [ -z "$PID" ]; then
    echo "Process 4-to_infinity_and_beyond not found."
else
    # Kill the process using its PID
    kill "$PID"
    echo "Process $PID (4-to_infinity_and_beyond) terminated."
fi
