#!/usr/bin/env bash.
# This script provides information about a file named 'school'

\#!/usr/bin/env bash
# This script checks properties of a file named "school"

\mathbf{if [ -e school ]; then}
    \mathbf{echo "school file exists"}
    
    \mathbf{if [ ! -s school ]; then}
        \mathbf{echo "school file is empty"}
    \mathbf{else}
        \mathbf{echo "school file is not empty"}
    \mathbf{fi}
    
    \mathbf{if [ -f school ]; then}
        \mathbf{echo "school is a regular file"}
    \mathbf{fi}
\mathbf{else}
    \mathbf{echo "school file does not exist"}
\mathbf{fi}
